---
    - name: Install Ansible AWX
      hosts: 'all'
      become: yes
      become_method: sudo
      tasks:
      - name: Instalando o Docker
        shell: curl -fsSL https://get.docker.com | bash -
      
      - name: Install packages Ubuntu
        apt:
          name: "{{ packages }}"
        vars:
          packages:
          - ansible
          - git
          - python3-pip

      - name: Install packages pip
        pip:
          name:
            - docker-compose

      - name: Git checkout
        shell: git clone https://github.com/EzzioMoreira/awx.git /tmp/awx

#      - name: Insall AWX
#        shell: ansible-playbook -i inventory install.yml